// ============================================================
// DATA.JS — TürkUA Savaş Takip Verileri
// Otomatik güncelleme: Zamanlanmış görev tarafından yönetilir.
// ============================================================
// DATA_START
window.WAR_DATA = {
  "prob1d": 2,
  "prob1m": 7,
  "prob1y": 34,
  "confidence": 3,
  "lastUpdate": "2026-04-04T12:00:00",
  "trendPct": 30,
  "statusSavas": { "tr": "AKTİF", "ua": "АКТИВНА" },
  "statusMuzakere": { "tr": "DURDU", "ua": "ЗУПИНЕНО" },
  "trend": { "tr": "düşük / sabit", "ua": "низький / стабільний" },
  "label1d": { "tr": "Paskalya ateşkesi reddedildi, cephe durağan", "ua": "Великоднє перемир'я відхилено, фронт стабільний" },
  "label1m": { "tr": "Rusya müzakereden kaçınıyor, Peskov koşul öne sürdü", "ua": "Росія уникає переговорів, Пєсков висунув умови" },
  "label1y": { "tr": "Koalisyon güvenlik garantileri şekilleniyor, ateşkes penceresi açık", "ua": "Гарантії безпеки коаліції формуються, вікно для перемир\'я відкрите" },
  "reasoning": {
    "tr": "Nisan 2026 başında müzakere süreci durma noktasında. Zelenskiy'nin Ortodoks Paskalya ateşkes önerisini Rusya reddetti. Kremlin sözcüsü Peskov, Ukrayna'nın Donbas'tan çekilmesini ön koşul olarak ileri sürdü. ISW verilerine göre Rusya Mart 2026'da 17 mil kare toprak kazandı. Erdoğan, Putin ile telefon görüşmesinde Türkiye'nin arabuluculuk girişimlerini sürdürdüğünü belirtti. İngiltere ve Fransa, ateşkes sonrasında Ukrayna'da askeri üs kuracaklarını duyurdu.",
    "ua": "На початку квітня 2026 р. переговорний процес зупинився. Росія відхилила пропозицію Зеленського про православне великоднє перемир'я. Пєсков висунув передумову — відведення українських сил з Донбасу. За даними ISW, у березні Росія захопила 17 кв. миль. Ердоган у розмові з Путіним підтвердив посередницькі зусилля Туреччини. Великобританія та Франція оголосили про розгортання військових баз в Україні після ймовірного перемир'я."
  },
  "developments": [
    { "date": { "tr": "4 Nisan 2026", "ua": "4 квітня 2026" }, "text": { "tr": "Erdoğan-Putin telefon görüşmesinde Ukrayna savaşı, İran gelişmeleri ve Suriye ele alındı. Erdoğan barışçıl çözüm için Türkiye'nin arabuluculuğunu sürdüreceğini vurguladı.", "ua": "Ердоган і Путін по телефону обговорили війну в Україні, ситуацію в Ірані та Сирію. Ердоган підтвердив посередницьку роль Туреччини." }, "impact": 1, "type": "positive" },
    { "date": { "tr": "1 Nisan 2026", "ua": "1 квітня 2026" }, "text": { "tr": "Rusya, Zelenskiy'nin Ortodoks Paskalya ateşkes önerisini reddetti. Peskov, Donbas'tan Ukrayna askerlerinin çekilmesini ön koşul olarak öne sürdü.", "ua": "Росія відхилила пропозицію Зеленського про великоднє перемир'я. Пєсков висунув передумову — відведення українських військ з Донбасу." }, "impact": -2, "type": "negative" },
    { "date": { "tr": "1 Nisan 2026", "ua": "1 квітня 2026" }, "text": { "tr": "Zelenskiy ve NATO Genel Sekreteri Rutte, ABD güvenlik garantileri çerçevesini görüştü. Ukrayna seçimlerin ancak ateşkes sonrası yapılabileceğini belirtti.", "ua": "Зеленський і генсек НАТО Рютте обговорили рамки гарантій безпеки США. Київ: вибори — лише після перемир'я." }, "impact": 1, "type": "positive" },
    { "date": { "tr": "31 Mart 2026", "ua": "31 березня 2026" }, "text": { "tr": "Ukrayna insansız hava araçları Rus Ust-Luga limanını son 10 günde 5. kez vurdu. Rusya'nın ham petrol ihracatı sekteye uğradı.", "ua": "Українські дрони вдарили по Усть-Лузі вп'яте за 10 днів. Експорт нафти Росії ускладнений." }, "impact": 2, "type": "positive" },
    { "date": { "tr": "3 Nisan 2026", "ua": "3 квітня 2026" }, "text": { "tr": "Rusya, gece-gündüz birleştiren yeni toplu drone taktiğiyle Ukrayna'ya 700+ insansız hava aracı fırlattı. ISW yeni saldırı modelini belgeledi.", "ua": "Росія застосувала нову тактику — 700+ дронів вдень і вночі. ISW задокументував новий тип масованих ударів." }, "impact": -3, "type": "negative" },
    { "date": { "tr": "Mart 2026", "ua": "Березень 2026" }, "text": { "tr": "Macaristan'ın vetosyla AB'nin 90 milyar Euro'luk Ukrayna Destek Kredisi bloke oldu.", "ua": "Угорщина заблокувала кредит ЄС для України на €90 млрд." }, "impact": -2, "type": "negative" }
  ],
  "newsItems": [
    { "category": "diplomatic", "date": { "tr": "4 Nisan 2026", "ua": "4 квітня 2026" }, "title": { "tr": "Erdoğan-Putin görüşmesi: Ukrayna ve İran gündemi", "ua": "Переговори Ердоган–Путін: Україна та Іран на порядку денному" }, "body": { "tr": "Cumhurbaşkanı Erdoğan ile Putin telefon görüşmesinde Ukrayna savaşı, İran'a yönelik saldırılar ve Suriye ele alındı. Erdoğan Türkiye'nin barışçıl çözüm için arabuluculuğunu sürdüreceğini vurguladı.", "ua": "Ердоган і Путін по телефону обговорили війну в Україні, удари по Ірану та Сирію. Ердоган підтвердив посередницьку роль Туреччини заради мирного врегулювання." }, "impact": 1, "type": "positive" },
    { "category": "diplomatic", "date": { "tr": "1 Nisan 2026", "ua": "1 квітня 2026" }, "title": { "tr": "Rusya Paskalya ateşkesini reddetti — Peskov Donbas koşulu öne sürdü", "ua": "Росія відхилила великоднє перемир'я — Пєсков вимагає відходу з Донбасу" }, "body": { "tr": "Kremlin sözcüsü Peskov, Zelenskiy'nin Paskalya ateşkes önerisini reddederek Ukrayna'nın Donbas'tan çekilmesini koşul olarak ileri sürdü.", "ua": "Пєсков відхилив пропозицію Зеленського і вимагає відведення українських сил з Донбасу як передумову переговорів." }, "impact": -2, "type": "negative" },
    { "category": "diplomatic", "date": { "tr": "1 Nisan 2026", "ua": "1 квітня 2026" }, "title": { "tr": "Zelenskiy-Rutte: ABD güvenlik garantileri çerçevesi netleşiyor", "ua": "Зеленський–Рютте: рамки гарантій безпеки США набирають форму" }, "body": { "tr": "Zelenskiy ve NATO Genel Sekreteri Rutte sanal görüşmede Ukrayna'nın savaş sonrası güvenlik garantileri çerçevesini görüştü. Ukrayna seçimlerin ancak ateşkes sonrası yapılabileceğini vurguladı.", "ua": "Зеленський і Рютте обговорили рамки повоєнних гарантій безпеки. Київ: вибори — лише після перемир'я та гарантій безпеки." }, "impact": 1, "type": "positive" },
    { "category": "military", "date": { "tr": "3 Nisan 2026", "ua": "3 квітня 2026" }, "title": { "tr": "ISW: Rusya 700+ drone ile yeni toplu taktik uyguladı", "ua": "ISW: Росія — 700+ дронів, нова тактика масованих ударів" }, "body": { "tr": "ISW'ye göre Rusya, 31 Mart–1 Nisan arasında gece ve gündüz birleştiren yeni toplu saldırı taktiğiyle 700'den fazla drone fırlattı. Lutsk, Jitomir, Hmelnytskiy ve Kriviy Rig'te patlamalar yaşandı.", "ua": "За даними ISW, між 31 березня та 1 квітня Росія застосувала нову тактику: понад 700 дронів вдень і вночі. Вибухи в Луцьку, Житомирі, Хмельницькому, Кривому Розі." }, "impact": -3, "type": "negative" },
    { "category": "military", "date": { "tr": "31 Mart 2026", "ua": "31 березня 2026" }, "title": { "tr": "Ukrayna Ust-Luga limanını 5. kez vurdu", "ua": "Україна вдарила по Усть-Лузі вп'яте за 10 днів" }, "body": { "tr": "Ukrayna insansız hava araçları Rus Ust-Luga limanını son 10 günde beşinci kez vurdu. Saldırı Rusya'nın ham petrol ihracatını sekteye uğratmayı amaçlıyor.", "ua": "Українські дрони вдарили по порту Усть-Луга — 5-й удар за 10 днів, спрямований на порушення нафтового експорту Росії." }, "impact": 2, "type": "positive" },
    { "category": "military", "date": { "tr": "1 Nisan 2026", "ua": "1 квітня 2026" }, "title": { "tr": "Rusya: Luhansk bölgesinin tamamı kontrol altında", "ua": "Росія заявила про повний контроль над Луганщиною" }, "body": { "tr": "Rusya Savunma Bakanlığı, Luhansk bölgesinin kurtarılmasının tamamlandığını duyurdu. ISW verilerine göre Ukrayna bölgenin yalnızca %0,2'sini kontrol ediyordu.", "ua": "Міноборони Росії оголосило про завершення звільнення Луганщини. За даними ISW, Україна контролювала лише 0,2% цієї області." }, "impact": -2, "type": "negative" },
    { "category": "diplomatic", "date": { "tr": "1 Nisan 2026", "ua": "1 квітня 2026" }, "title": { "tr": "12 AB dışişleri bakanı Buça 4. yıldönümünde Kyiv'de", "ua": "12 міністрів ЄС у Києві на 4-у річницю Бучі" }, "body": { "tr": "AB dış politika şefi Kaja Kallas ve 12 AB üyesi ülkenin dışişleri bakanları Kyiv'e giderek Buça katliamının 4. yıldönümünde Ukrayna'ya destek mesajı verdi.", "ua": "Каллас та 12 міністрів ЄС прибули до Києва з підтримкою України у 4-у річницю Бучі." }, "impact": 2, "type": "positive" },
    { "category": "economic", "date": { "tr": "Mart 2026", "ua": "Березень 2026" }, "title": { "tr": "EBRD: Ukrayna ekonomisi %2,5 büyüyecek", "ua": "ЄБРР: економіка України зросте на 2,5%" }, "body": { "tr": "Avrupa İmar ve Kalkınma Bankası, savaşın sürmesine rağmen Ukrayna'nın 2026'da %2,5, 2027'de %4 büyüyeceğini öngördü.", "ua": "ЄБРР прогнозує зростання ВВП України на 2,5% у 2026 р. та на 4% у 2027 р. попри тривання війни." }, "impact": 1, "type": "positive" }
  ],
  "gundemNews": [
    { "category": "diplomatic", "date": { "tr": "4 Nisan 2026", "ua": "4 квітня 2026" }, "title": { "tr": "Erdoğan-Putin: Ukrayna ve İran görüşüldü", "ua": "Ердоган–Путін: обговорили Україну та Іран" }, "body": { "tr": "Erdoğan ile Putin telefon görüşmesinde Ukrayna savaşı, İran'a yönelik saldırılar ve Suriye'deki gelişmeler ele alındı. Erdoğan barışçıl çözüm için Türkiye'nin arabuluculuğunu sürdüreceğini vurguladı.", "ua": "Ердоган і Путін по телефону обговорили війну в Україні, удари по Ірану та Сирію. Ердоган підтвердив посередницьку роль Туреччини." }, "url": "https://www.istiklal.com.tr/gundem/erdogan-putin-hattinda-kritik-gundem-1089321h", "impact": 1, "type": "positive" },
    { "category": "diplomatic", "date": { "tr": "1 Nisan 2026", "ua": "1 квітня 2026" }, "title": { "tr": "Rusya Paskalya ateşkesini reddetti — Peskov Donbas'tan çekilme şartı öne sürdü", "ua": "Росія відхилила великоднє перемир'я — Пєсков вимагає відходу з Донбасу" }, "body": { "tr": "Kremlin sözcüsü Peskov, Zelenskiy'nin Paskalya ateşkes önerisini reddederek Ukrayna'nın Donbas'tan çekilmesini koşul olarak ileri sürdü.", "ua": "Пєсков відхилив пропозицію Зеленського і вимагає відведення українських сил з Донбасу як передумову." }, "url": "https://www.cfr.org/global-conflict-tracker/conflict/conflict-ukraine", "impact": -2, "type": "negative" },
    { "category": "military", "date": { "tr": "3 Nisan 2026", "ua": "3 квітня 2026" }, "title": { "tr": "ISW: Rusya gece-gündüz 700+ drone ile yeni taktik uyguladı", "ua": "ISW: Росія застосувала нову тактику — 700+ дронів вдень і вночі" }, "body": { "tr": "Rusya, 31 Mart–1 Nisan arasında Ukrayna'ya gece ve gündüz birleştiren yeni toplu saldırı taktiğiyle 700'den fazla drone fırlattı.", "ua": "Між 31 березня та 1 квітня Росія застосувала нову тактику масованих атак вдень і вночі — понад 700 дронів." }, "url": "https://www.ukrhaber.com/blog/rusyanin-yeni-insansiz-hava-araci-saldiri-taktikleri-isw-tehlikeye-karsi-uyarida-bulunuyor-ve-iranla-karsilastiriyor/", "impact": -3, "type": "negative" },
    { "category": "military", "date": { "tr": "31 Mart 2026", "ua": "31 березня 2026" }, "title": { "tr": "Ukrayna Ust-Luga limanını 5. kez vurdu — Rus petrol ihracatı sekteye uğradı", "ua": "Україна 5-й раз вдарила по Усть-Лузі — нафтовий експорт Росії під загрозою" }, "body": { "tr": "Ukrayna insansız hava araçları Rus Ust-Luga limanını son 10 günde beşinci kez vurdu. Rusya'nın ham petrol ihracatını olumsuz etkiliyor.", "ua": "Українські дрони вдарили по порту Усть-Луга вп'яте за 10 днів, ускладнюючи експорт сирої нафти Росії." }, "url": "https://www.cfr.org/global-conflict-tracker/conflict/conflict-ukraine", "impact": 2, "type": "positive" },
    { "category": "military", "date": { "tr": "1 Nisan 2026", "ua": "1 квітня 2026" }, "title": { "tr": "ISW: Rusya Mart'ta 17 mil kare toprak kazandı", "ua": "ISW: у березні Росія захопила 17 кв. миль території" }, "body": { "tr": "ISW verilerine göre Rusya, Mart 2026'da Ukrayna'da 17 mil kare toprak kazandı. Son 12 ayda aylık ortalama kazanım 160 mil kare. Ukrayna ise güneyde 154 mil kare geri aldı.", "ua": "За даними ISW, у березні 2026 р. Росія захопила 17 кв. миль. Середньомісячний приріст — 160 кв. миль. Україна повернула 154 кв. миль на півдні." }, "url": "https://www.russiamatters.org/news/russia-ukraine-war-report-card/russia-ukraine-war-report-card-april-1-2026", "impact": -2, "type": "negative" },
    { "category": "diplomatic", "date": { "tr": "1 Nisan 2026", "ua": "1 квітня 2026" }, "title": { "tr": "12 AB dışişleri bakanı Buça 4. yıldönümünde Kyiv'de", "ua": "12 міністрів ЄС у Києві на 4-у річницю Бучі" }, "body": { "tr": "AB dış politika şefi Kallas ve 12 AB dışişleri bakanı Kyiv'e giderek Buça katliamının 4. yıldönümünde Ukrayna'ya destek verdi.", "ua": "Каллас та 12 міністрів ЄС прибули до Києва і підтримали Україну в 4-у річницю Бучі." }, "url": "https://www.euractiv.com", "impact": 2, "type": "positive" },
    { "category": "economic", "date": { "tr": "26 Mart 2026", "ua": "26 березня 2026" }, "title": { "tr": "Rada: Mali kriz uyarısı — 3,9 milyar Euro havada", "ua": "Рада: попередження про фінансову кризу — €3,9 млрд під загрозою" }, "body": { "tr": "Rada vergi komitesi başkanı, Ukrayna'nın Ukraine Facility programının 14 şartını yerine getirememesi nedeniyle 3,9 milyar Euro'yu alamadığını açıkladı.", "ua": "Голова комітету Ради заявив, що Україна не отримала €3,9 млрд через невиконання 14 вимог програми Ukraine Facility." }, "url": "https://ua.news-pravda.com/en/world/2026/03/26/94143.html", "impact": -2, "type": "negative" },
    { "category": "economic", "date": { "tr": "Mart 2026", "ua": "Березень 2026" }, "title": { "tr": "EBRD: Ukrayna ekonomisi %2,5 büyüyecek", "ua": "ЄБРР: економіка України зросте на 2,5%" }, "body": { "tr": "Avrupa İmar ve Kalkınma Bankası, savaşın sürmesine rağmen Ukrayna'nın 2026'da %2,5, 2027'de %4 büyüyeceğini öngördü.", "ua": "ЄБРР прогнозує зростання ВВП України на 2,5% у 2026 р. та на 4% у 2027 р. попри тривання війни." }, "url": "https://www.ebrd.com/home/news-and-events/news/2026/ukraine-maintains-macroeconomic-stability-despite-war---ebrd-rep.html", "impact": 1, "type": "positive" }
  ],
  "gundemLastUpdate": "2026-04-04T12:00:00"
};
// DATA_END